import '@digital-wolf/styles';
import '../styles/global.scss';
import { ReactNode } from 'react';
import { EntryPointLayoutView } from '../layouts/EntryPointLayoutView';
import { UiMaterialToastMessageProvider } from '@digital-wolf/ui-material';
import { SystemContextProvider } from '../context/SystemContext';
import { UserContextProvider } from '@digital-wolf/context-api';
import { UtilsHead } from '@digital-wolf/utils';
import '@digital-wolf/ui-styles-utils';
import '@digital-wolf/ui-styles-features/drag-and-drop';
import { BasicInfoContextProvider } from '../context/BasicInfoContext';

export const metadata = {
  title: 'Welcome to Seven Arch',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <UtilsHead />
      <body>
        <SystemContextProvider>
          <UserContextProvider>
            <BasicInfoContextProvider>
              <UiMaterialToastMessageProvider>
                <EntryPointLayoutView>{children}</EntryPointLayoutView>
              </UiMaterialToastMessageProvider>
            </BasicInfoContextProvider>
          </UserContextProvider>
        </SystemContextProvider>
      </body>
    </html>
  );
}
