import '../styles/global.scss';
import { BaseContainer } from '../containers/BaseContainer';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Welcome to cv-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <BaseContainer>{children}</BaseContainer>
      </body>
    </html>
  );
}
